<?php
require_once __DIR__ . '/includes/auth.php';
require_admin();
$id=get_query_param('user_id'); if($id===''||!ctype_digit($id)||(int)$id<=0){set_flash('error','ユーザーIDが正しくありません。');redirect('admin_users.php');}
$targetUserId=(int)$id; $pdo=db();
$stmt=$pdo->prepare('SELECT id,username,is_admin,is_suspended,created_at,updated_at,last_login_at,suspended_at,suspended_reason FROM users WHERE id=:id'); $stmt->execute([':id'=>$targetUserId]); $user=$stmt->fetch(); if(!$user){set_flash('error','ユーザーが見つかりません。');redirect('admin_users.php');}
$counts=[]; foreach(['diary_count'=>'diaries','crop_count'=>'crops','field_count'=>'fields','expense_count'=>'expenses','sale_count'=>'sales'] as $k=>$t){$st=$pdo->prepare("SELECT COUNT(*) FROM $t WHERE user_id=:uid");$st->execute([':uid'=>$targetUserId]);$counts[$k]=(int)$st->fetchColumn();}
$st=$pdo->prepare('SELECT COALESCE(SUM(amount),0) FROM expenses WHERE user_id=:uid');$st->execute([':uid'=>$targetUserId]);$expenseTotal=(int)$st->fetchColumn();
$st=$pdo->prepare('SELECT COALESCE(SUM(gross_amount),0) FROM sales WHERE user_id=:uid');$st->execute([':uid'=>$targetUserId]);$saleTotal=(int)$st->fetchColumn();
$canSuspend=(int)$user['is_admin']!==1 && (int)$user['id']!==current_user_id();
$pageTitle='ユーザー詳細 | 管理者画面 | '.APP_NAME; include __DIR__.'/includes/header.php';
?>
<section class="card admin-hero"><h2>管理者専用：ユーザー詳細</h2><p class="description">必要最小限の利用状況だけを表示します。パスワード情報と削除機能はありません。</p><div class="button-row"><a class="btn" href="admin_users.php">ユーザー一覧へ戻る</a><a class="btn" href="admin_dashboard.php">管理者ダッシュボードへ戻る</a></div></section>
<section class="card"><h3>基本情報</h3><dl class="detail-grid admin-detail-grid"><dt>ユーザーID</dt><dd><?= e($user['id']) ?></dd><dt>ユーザー名</dt><dd><?= e($user['username']) ?></dd><dt>権限</dt><dd><span class="badge <?= (int)$user['is_admin']===1?'badge-admin':'badge-user' ?>"><?= (int)$user['is_admin']===1?'管理者':'一般ユーザー' ?></span></dd><dt>状態</dt><dd><span class="badge <?= (int)$user['is_suspended']===1?'badge-danger':'badge-success' ?>"><?= (int)$user['is_suspended']===1?'停止中':'通常' ?></span></dd><dt>登録日時</dt><dd><?= e($user['created_at']) ?></dd><dt>更新日時</dt><dd><?= e($user['updated_at'] ?? '-') ?></dd><dt>最終ログイン日時</dt><dd><?= e($user['last_login_at'] ?? '-') ?></dd><dt>停止日時</dt><dd><?= e($user['suspended_at'] ?? '-') ?></dd><dt>停止理由</dt><dd><?= nl2br(e($user['suspended_reason'] ?? '-')) ?></dd></dl></section>
<section class="card"><h3>利用状況サマリー</h3><div class="summary-grid admin-summary-grid"><?php foreach([['日誌件数',$counts['diary_count']],['作物件数',$counts['crop_count']],['圃場件数',$counts['field_count']],['経費件数',$counts['expense_count']],['売上件数',$counts['sale_count']],['経費合計',format_yen($expenseTotal)],['売上合計',format_yen($saleTotal)]] as $c): ?><div class="summary-card"><span><?= e($c[0]) ?></span><strong><?= e($c[1]) ?></strong></div><?php endforeach; ?></div></section>
<section class="card danger-zone"><h3>停止操作</h3><?php if(!$canSuspend): ?><p class="alert error">自分自身または管理者ユーザーは停止できません。</p><?php elseif((int)$user['is_suspended']===1): ?><form method="post" action="admin_user_suspend.php" onsubmit="return confirm('停止を解除しますか？');"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="user_id" value="<?= e($user['id']) ?>"><input type="hidden" name="action" value="unsuspend"><button class="btn primary" type="submit">停止を解除する</button></form><?php else: ?><form method="post" action="admin_user_suspend.php" class="stack" onsubmit="return confirm('このユーザーを停止しますか？');"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="user_id" value="<?= e($user['id']) ?>"><input type="hidden" name="action" value="suspend"><label>停止理由<textarea name="suspended_reason" rows="4" required placeholder="不正利用の疑い、迷惑行為、利用規約違反、その他"></textarea></label><button class="btn danger" type="submit">このユーザーを停止する</button></form><?php endif; ?></section>
<?php include __DIR__.'/includes/footer.php'; ?>
