<?php
require_once __DIR__ . '/includes/auth.php';
require_admin();
$pdo = db();
$keyword = trim(get_query_param('q'));
$role = get_query_param('role','all'); if(!in_array($role,['all','admin','user'],true)) $role='all';
$status = get_query_param('status','all'); if(!in_array($status,['all','active','suspended'],true)) $status='all';
$login = get_query_param('login','all'); if(!in_array($login,['all','yes','no'],true)) $login='all';
$pageParam = get_query_param('page','1'); $page = ctype_digit($pageParam) ? max(1,(int)$pageParam) : 1; $perPage=20; $offset=($page-1)*$perPage;
$where=[]; $params=[];
if($keyword!==''){ $where[]='u.username LIKE :keyword'; $params[':keyword']='%'.$keyword.'%'; }
if($role==='admin') $where[]='u.is_admin=1'; elseif($role==='user') $where[]='u.is_admin=0';
if($status==='active') $where[]='COALESCE(u.is_suspended,0)=0'; elseif($status==='suspended') $where[]='COALESCE(u.is_suspended,0)=1';
if($login==='yes') $where[]='u.last_login_at IS NOT NULL'; elseif($login==='no') $where[]='u.last_login_at IS NULL';
$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$count=$pdo->prepare("SELECT COUNT(*) FROM users u $whereSql"); $count->execute($params); $totalRows=(int)$count->fetchColumn(); $totalPages=max(1,(int)ceil($totalRows/$perPage)); if($page>$totalPages){$page=1;$offset=0;}
$sql="SELECT u.id,u.username,u.is_admin,u.is_suspended,u.created_at,u.updated_at,u.last_login_at,COUNT(DISTINCT d.id) diary_count,COUNT(DISTINCT e.id) expense_count,COUNT(DISTINCT s.id) sale_count FROM users u LEFT JOIN diaries d ON d.user_id=u.id LEFT JOIN expenses e ON e.user_id=u.id LEFT JOIN sales s ON s.user_id=u.id $whereSql GROUP BY u.id ORDER BY datetime(u.created_at) DESC,u.id DESC LIMIT :limit OFFSET :offset";
$stmt=$pdo->prepare($sql); foreach($params as $k=>$v)$stmt->bindValue($k,$v); $stmt->bindValue(':limit',$perPage,PDO::PARAM_INT); $stmt->bindValue(':offset',$offset,PDO::PARAM_INT); $stmt->execute(); $users=$stmt->fetchAll();
$base=['q'=>$keyword,'role'=>$role,'status'=>$status,'login'=>$login]; $url=fn($p)=>'admin_users.php?'.http_build_query(array_merge($base,['page'=>$p]));
$pageTitle='ユーザー一覧 | 管理者画面 | '.APP_NAME; include __DIR__.'/includes/header.php';
?>
<section class="card admin-hero"><h2>管理者専用：ユーザー一覧</h2><p class="description">パスワードハッシュは表示しません。ユーザー削除機能はありません。</p><div class="button-row"><a class="btn" href="admin_dashboard.php">管理者ダッシュボードへ戻る</a></div></section>
<section class="card"><h3>検索・絞り込み</h3><form method="get" class="search-form"><div class="filter-grid"><label>ユーザー名検索<input name="q" value="<?= e($keyword) ?>"></label><label>権限<select name="role"><option value="all">すべて</option><option value="admin" <?= $role==='admin'?'selected':'' ?>>管理者</option><option value="user" <?= $role==='user'?'selected':'' ?>>一般ユーザー</option></select></label><label>状態<select name="status"><option value="all">すべて</option><option value="active" <?= $status==='active'?'selected':'' ?>>通常</option><option value="suspended" <?= $status==='suspended'?'selected':'' ?>>停止中</option></select></label><label>最終ログイン<select name="login"><option value="all">すべて</option><option value="yes" <?= $login==='yes'?'selected':'' ?>>あり</option><option value="no" <?= $login==='no'?'selected':'' ?>>なし</option></select></label></div><div class="button-row"><button class="primary">検索する</button><a class="btn" href="admin_users.php">クリア</a></div></form><p class="description">該当件数: <?= e($totalRows) ?>件 / <?= e($page) ?>ページ目</p></section>
<section class="card"><h3>ユーザー一覧</h3><div class="table-wrap"><table class="admin-table admin-users-table"><thead><tr><th>ID</th><th>ユーザー名</th><th>権限</th><th>状態</th><th>登録日</th><th>更新日</th><th>最終ログイン</th><th>日誌</th><th>経費</th><th>売上</th><th>詳細</th></tr></thead><tbody><?php foreach($users as $u): ?><tr class="<?= (int)$u['is_suspended']===1?'is-suspended':'' ?>"><td><?= e($u['id']) ?></td><td><?= e($u['username']) ?></td><td><span class="badge <?= (int)$u['is_admin']===1?'badge-admin':'badge-user' ?>"><?= (int)$u['is_admin']===1?'管理者':'一般ユーザー' ?></span></td><td><span class="badge <?= (int)$u['is_suspended']===1?'badge-danger':'badge-success' ?>"><?= (int)$u['is_suspended']===1?'停止中':'通常' ?></span></td><td><?= e($u['created_at']) ?></td><td><?= e($u['updated_at'] ?? '-') ?></td><td><?= e($u['last_login_at'] ?? '-') ?></td><td><?= e($u['diary_count']) ?></td><td><?= e($u['expense_count']) ?></td><td><?= e($u['sale_count']) ?></td><td><a class="btn small" href="admin_user_detail.php?user_id=<?= e($u['id']) ?>">詳細</a></td></tr><?php endforeach; if(!$users): ?><tr><td colspan="11">条件に一致するユーザーはいません。</td></tr><?php endif; ?></tbody></table></div><?php if($totalPages>1): ?><nav class="pagination"><?php if($page>1): ?><a class="btn small" href="<?= e($url($page-1)) ?>">前へ</a><?php endif; ?><span><?= e($page) ?> / <?= e($totalPages) ?></span><?php if($page<$totalPages): ?><a class="btn small" href="<?= e($url($page+1)) ?>">次へ</a><?php endif; ?></nav><?php endif; ?></section>
<?php include __DIR__.'/includes/footer.php'; ?>
