<?php
require_once __DIR__.'/includes/auth.php'; require_admin(); $pdo=db();
$q=trim(get_query_param('q')); $status=get_query_param('status','all'); if(!in_array($status,['all','subscribed','unsubscribed','not_subscribed'],true))$status='all';
$sort=get_query_param('sort','newest'); if(!in_array($sort,['newest','oldest'],true))$sort='newest';
$where=[];$params=[]; if($q!==''){ $where[]='(u.username LIKE :q OR u.email LIKE :q)';$params[':q']='%'.$q.'%'; } if($status!=='all'){$where[]='s.status=:status';$params[':status']=$status;}
$whereSql=$where?'WHERE '.implode(' AND ',$where):''; $order=$sort==='oldest'?'ASC':'DESC';
$summary=$pdo->query("SELECT COUNT(*) total,SUM(s.status='subscribed') subscribed,SUM(s.status='unsubscribed') unsubscribed,SUM(s.status='not_subscribed') not_subscribed FROM users u JOIN email_subscriptions s ON s.user_id=u.id")->fetch();
if(get_query_param('format')==='csv'){
 if(!verify_csrf_token(get_query_param('token'))){http_response_code(403);exit('不正なリクエストです。');}
 $stmt=$pdo->prepare("SELECT u.id user_id,u.username,u.email,s.status subscription_status,u.created_at registered_at,s.subscribed_at,s.unsubscribed_at,CASE WHEN COALESCE(u.is_suspended,0)=1 THEN 'suspended' ELSE 'active' END account_status FROM users u JOIN email_subscriptions s ON s.user_id=u.id $whereSql ORDER BY datetime(u.created_at) $order,u.id $order");$stmt->execute($params);
 log_admin_action(current_user_id(),'メールアドレスCSV出力','email_subscription',null,'status='.$status);
 header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="email_subscriptions.csv"');header('Cache-Control: no-store, no-cache, must-revalidate');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,['user_id','username','email','subscription_status','registered_at','subscribed_at','unsubscribed_at','account_status']);
 while($row=$stmt->fetch()){foreach($row as &$v){$v=(string)$v;if(preg_match('/^[=+\-@]/',$v))$v="'".$v;}unset($v);fputcsv($out,$row);}fclose($out);exit;
}
$page=max(1,(int)get_query_param('page','1'));$perPage=25;$count=$pdo->prepare("SELECT COUNT(*) FROM users u JOIN email_subscriptions s ON s.user_id=u.id $whereSql");$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);
$stmt=$pdo->prepare("SELECT u.id,u.username,u.email,u.created_at,u.is_suspended,s.status,s.subscribed_at,s.unsubscribed_at FROM users u JOIN email_subscriptions s ON s.user_id=u.id $whereSql ORDER BY datetime(u.created_at) $order,u.id $order LIMIT :limit OFFSET :offset");foreach($params as $k=>$v)$stmt->bindValue($k,$v);$stmt->bindValue(':limit',$perPage,PDO::PARAM_INT);$stmt->bindValue(':offset',($page-1)*$perPage,PDO::PARAM_INT);$stmt->execute();$rows=$stmt->fetchAll();
$base=['q'=>$q,'status'=>$status,'sort'=>$sort];$pageTitle='メール配信 | 管理者画面 | '.APP_NAME;include __DIR__.'/includes/header.php';
?>
<section class="card admin-hero"><h2>メール配信管理</h2><p class="description">登録メールと案内メールへの同意を分離して管理します。</p><div class="button-row"><a class="btn primary" href="admin_email_campaign.php">メールを作成</a><a class="btn" href="admin_email_campaigns.php">配信履歴</a><a class="btn" href="admin_dashboard.php">管理画面へ戻る</a></div></section>
<section class="stats-grid"><article class="card"><strong><?= e($summary['total']) ?></strong><span>登録ユーザー</span></article><article class="card"><strong><?= e($summary['subscribed']) ?></strong><span>配信同意済み</span></article><article class="card"><strong><?= e($summary['unsubscribed']) ?></strong><span>配信停止</span></article><article class="card"><strong><?= e($summary['not_subscribed']) ?></strong><span>未同意</span></article></section>
<section class="card"><form method="get" class="filter-grid"><label>キーワード<input name="q" value="<?= e($q) ?>"></label><label>配信状態<select name="status"><option value="all">すべて</option><?php foreach(['subscribed'=>'配信中','unsubscribed'=>'配信停止','not_subscribed'=>'未同意'] as $v=>$l):?><option value="<?=e($v)?>" <?=$status===$v?'selected':''?>><?=e($l)?></option><?php endforeach?></select></label><label>登録日<select name="sort"><option value="newest" <?=$sort==='newest'?'selected':''?>>新しい順</option><option value="oldest" <?=$sort==='oldest'?'selected':''?>>古い順</option></select></label><div class="button-row"><button class="primary">検索</button><a class="btn" href="admin_emails.php">クリア</a></div></form><a class="btn" href="?<?=e(http_build_query(array_merge($base,['format'=>'csv','token'=>csrf_token()])))?>">CSV出力</a></section>
<section class="card"><div class="table-wrap"><table class="admin-table"><thead><tr><th>ID</th><th>ユーザー名</th><th>メール</th><th>配信状態</th><th>登録日</th><th>同意日</th><th>停止日</th><th>アカウント</th></tr></thead><tbody><?php foreach($rows as $r):$labels=['subscribed'=>'配信中','unsubscribed'=>'配信停止','not_subscribed'=>'未同意'];?><tr><td><?=e($r['id'])?></td><td><?=e($r['username'])?></td><td><?=e($r['email'])?></td><td><span class="badge <?=$r['status']==='subscribed'?'badge-success':($r['status']==='unsubscribed'?'badge-danger':'badge-user')?>"><?=e($labels[$r['status']])?></span></td><td><?=e($r['created_at'])?></td><td><?=e($r['subscribed_at']??'-')?></td><td><?=e($r['unsubscribed_at']??'-')?></td><td><?=((int)$r['is_suspended']===1)?'<span class="badge badge-danger">停止</span>':'<span class="badge badge-success">有効</span>'?></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="8">該当データはありません。</td></tr><?php endif?></tbody></table></div><nav class="pagination"><?php if($page>1):?><a class="btn small" href="?<?=e(http_build_query(array_merge($base,['page'=>$page-1])))?>">前へ</a><?php endif?><span><?=e($page)?> / <?=e($pages)?></span><?php if($page<$pages):?><a class="btn small" href="?<?=e(http_build_query(array_merge($base,['page'=>$page+1])))?>">次へ</a><?php endif?></nav></section>
<?php include __DIR__.'/includes/footer.php';
