<?php
require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/email_delivery.php';require_admin();$pdo=db();$id=(int)get_query_param('id','0');$s=$pdo->prepare('SELECT * FROM email_campaigns WHERE id=:id');$s->execute([':id'=>$id]);$c=$s->fetch();if(!$c){http_response_code(404);exit('キャンペーンが見つかりません。');}
$count=(int)$pdo->query("SELECT COUNT(*) FROM users u JOIN email_subscriptions s ON s.user_id=u.id WHERE s.status='subscribed' AND COALESCE(u.is_suspended,0)=0 AND u.email<>''")->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf_token($_POST['csrf_token']??null)){set_flash('error','不正なリクエストです。');redirect('admin_email_confirm.php?id='.$id);}
 $pdo->beginTransaction();try{$lock=$pdo->prepare("UPDATE email_campaigns SET status='queued',queued_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='draft'");$lock->execute([':id'=>$id]);if($lock->rowCount()!==1)throw new RuntimeException('already queued');
 $ins=$pdo->prepare("INSERT OR IGNORE INTO email_campaign_recipients(campaign_id,user_id,email,status) SELECT :id,u.id,u.email,'queued' FROM users u JOIN email_subscriptions s ON s.user_id=u.id WHERE s.status='subscribed' AND COALESCE(u.is_suspended,0)=0 AND u.email<>''");$ins->execute([':id'=>$id]);refresh_campaign_counts($id);$pdo->commit();log_admin_action(current_user_id(),'メール配信開始','email_campaign',$id,'recipients='.$count);set_flash('success','配信キューへ登録しました。');redirect('admin_email_campaigns.php');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();set_flash('error','すでにキュー登録済みか、処理に失敗しました。');redirect('admin_email_campaigns.php');}
}
$pageTitle='送信確認 | '.APP_NAME;include __DIR__.'/includes/header.php';?>
<section class="card"><h2>送信確認</h2><dl class="detail-grid"><dt>件名</dt><dd><?=e($c['subject'])?></dd><dt>本文</dt><dd><pre class="mail-preview"><?=e($c['body_text'])?></pre></dd><dt>配信対象</dt><dd>配信同意済みの有効ユーザー</dd><dt>配信予定人数</dt><dd><?=e($count)?>人</dd><dt>送信元</dt><dd><?=e(MAIL_FROM_NAME)?> &lt;<?=e(MAIL_FROM_ADDRESS)?>&gt;</dd><dt>返信先</dt><dd><?=e(MAIL_REPLY_TO)?></dd></dl><p class="alert error">開始後は件名・本文を変更できません。</p><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><button class="primary" type="submit">配信を開始する</button> <a class="btn" href="admin_email_campaign.php?id=<?=e($id)?>">修正する</a></form></section>
<?php include __DIR__.'/includes/footer.php';
